Charm to support ipv6 addresses in urls within templates and relation data
charmed-kubernetes/layer-etcd pull request #208
Opened 2023-03-15 20:16 UTC by addyess

urls with ipv6 addresses cannot be rendered as `https://${address}:${port}` because the address itself contains colons

instead each URL must be rendered as `https://[${address}]:${port}`

this PR creates a new `build_uri` method and uses it everywhere previous urls were being created. 

It takes care to ensure that ipv4 addresses remain the same, ipv6 addresses are handled correctly, and anything else is handled the same as a ipv4.

2023-03-15 21:27 UTC, Cynerva requested changes
I think get_connection_string needs the same treatment [here](https://github.com/charmed-kubernetes/layer-etcd/blob/900e72bd2072c2c9d386ca8c64b895b3c6122413/lib/etcdctl.py#L208), to fix the connection string that's used in a variety of etcdctl calls and also sent to peers and clients via relations. Other than that, this all looks good to me.

2023-03-15 21:47 UTC, addyess commented on lib/etcdctl.py
> +        connections.append(build_uri(protocol, address, port))
@Cynerva terrific spot!  thank you

2023-03-15 21:50 UTC, addyess commented on lib/etcd_lib.py
> +    return sorted(all_addrs, key=lambda i: ip_address(i).version)[0]
sort the addresses in such a way that ipv4 pops to the top first:

notice that python `sorted` doesn't alter any other order  (ie -- it doesn't deep sort)

```python
>>> i = [1,4,"a",3,"b",5]
>>> sorted(i, key=lambda k: type(k).__name__)
[1, 4, 3, 5, 'a', 'b']
```

2023-03-15 21:51 UTC, addyess commented on lib/etcd_lib.py
> +        )
sort the addresses from the `bind-addresses` by ipv4 first

2023-03-16 20:40 UTC, Cynerva approved these changes
:+1:

2023-03-20 20:36 UTC, merged