LP2053031: Adding tuning params
charmed-kubernetes/layer-etcd pull request #213
Opened 2024-03-25 00:15 UTC by FrancescoDeSimone

this PR add tuning parameters like heartbeat_interval, election_timeout, snapshot_count, as describe in LP:#2053031

2024-11-27 07:47 UTC, reneradoi commented
Hello @FrancescoDeSimone, I'm not sure if you saw the reply on Matrix, that's why I'll leave [my comment](https://matrix.to/#/!BukWfnyOTgQSKAxdtT:ubuntu.com/$MC9QtBgbJuOSn5QZ9VyPUxEpcN7Fuc0UGTlq89lKRNM?via=ubuntu.com&via=matrix.org&via=laquadrature.net) here as well. Please refer here for further discussion.

2025-01-16 21:40 UTC, addyess requested changes
Thank you so much for this PR and bringing attention to it.  I hope to start a good conversation around this bug.  So far the work looks good i only have a problem with the default for `snapshot_count`

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +    default: 10000
the default for this seems off:

https://etcd.io/docs/v3.4/op-guide/configuration/
> **--snapshot-count**
    Number of committed transactions to trigger a snapshot to disk.
    default: “100000”
    env variable: ETCD_SNAPSHOT_COUNT

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +      By default, snapshots will be made after every 10,000 changes.
```suggestion
      By default, snapshots will be made after every 100,000 changes.
```

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +      By default, etcd uses a 1000ms election timeout.
this default matches the docs

> **--election-timeout**
    Time (in milliseconds) for an election to timeout. See [Documentation/tuning.md](https://etcd.io/docs/v3.4/tuning/#time-parameters) for details.
    default: “1000”
    env variable: ETCD_ELECTION_TIMEOUT

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +      still the leader. By default, etcd uses a 100ms heartbeat interval.
This default matches the docs

> **--heartbeat-interval**
    Time (in milliseconds) of a heartbeat interval.
    default: “100”
    env variable: ETCD_HEARTBEAT_INTERVAL

2025-01-16 21:40 UTC, addyess commented on lib/etcd_databag.py
> +     'snapshot-count': '10000',
match the default in `config.yaml`
```suggestion
     'snapshot-count': '100000',
```

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +    default: 10000
but it seems when etcd [3.1] was released the default was much lower.  The default bumped in [3.2] but the charm didn't change to reflect that.  I think i'd rather new deployments or upgrades move to the new default.

A charm upgrade using this change would affect them.  I'm not sure quite how to proceed given that for many years, we've had a poor default in here starting with etcd [3.2] and beyond.

[3.1]: https://etcd.io/docs/v3.1/op-guide/configuration/
[3.2]: https://etcd.io/docs/v3.2/op-guide/configuration/

2025-01-16 21:40 UTC, addyess commented on templates/etcd3.conf
> +snapshot-count: {{ snapshot_count }}
I like this improvement to make that `snapshot-count` managed in the charm, along with the other two

2025-01-16 21:40 UTC, addyess commented on config.yaml
> +    default: 10000
Maybe this needs a default like `auto`.

if `auto`, we consult the `channel`.  any channel `>3.2`, let's use `100000`, channel <= `3.1`, use `10000`
  * if auto and there's no `.conf` file written -- use these above defaults
  * if auto and the file is written (likely an upgrade) -- maintain the values from the `conf` file
if NOT `auto` -- then we always override the value in the conf file.

This is the best way i can think to preserve existing cluster configurations while also improving the default snapshot_count for future fresh installs of etcd.  It'd be a poor choice for EVERY new etcd installation to require them to set `snapshot_count: 100000` just b/c we got the default wrong 8 years ago

2025-01-22 06:39 UTC, FrancescoDeSimone commented on config.yaml
> +    default: 10000
thank you @addyess added that

2025-01-22 12:00 UTC, HomayoonAlimohammadi reviewed
Great work, thanks a lot @FrancescoDeSimone! Left some comments and suggestions.

2025-01-22 12:00 UTC, HomayoonAlimohammadi commented on lib/etcd_lib.py
> +    return snapshot_count_number
Maybe we can change this to:
```suggestion
    try:
        return int(snapshot_count)
    except ValueError:
        raise TypeError(f"{snapshot_count} value is not an integer number")
```

2025-01-22 12:00 UTC, HomayoonAlimohammadi commented on tests/unit/lib/test_etcd_lib.py
> +from home.fdesi.git.layer-etcd.lib.__pycache__.etcd_lib import get_snapshot_count
I think this should be removed.

2025-01-22 12:00 UTC, HomayoonAlimohammadi commented on lib/etcd_lib.py
> +def get_snapshot_count(snapshot_count, channel):
```suggestion
def get_snapshot_count(snapshot_count: str, channel: str) -> int:
```

2025-01-22 12:00 UTC, HomayoonAlimohammadi commented on tests/unit/lib/test_etcd_lib.py
> +
```suggestion
def test_get_snapshot_count_auto_3_2():
    channel = "3.2"
    snapshot_count = "auto"
    assert get_snapshot_count(snapshot_count, channel) == 100000

def test_get_snapshot_count_auto_3_1():
    channel = "3.1"
    snapshot_count = "auto"
    assert get_snapshot_count(snapshot_count, channel) == 10000

def test_get_snapshot_count():
    channel = "3.1"
    snapshot_count = "100"
    assert get_snapshot_count(snapshot_count, channel) == int(snapshot_count)

```

2025-01-22 13:31 UTC, FrancescoDeSimone commented on tests/unit/lib/test_etcd_lib.py
> +from home.fdesi.git.layer-etcd.lib.__pycache__.etcd_lib import get_snapshot_count
ops, my lsp probably added

2025-01-22 18:38 UTC, addyess reviewed
Only a tiny nit remains.  Really nice work @FrancescoDeSimone 

can you check out the unit test failures?

2025-01-22 18:38 UTC, addyess commented on lib/etcd_lib.py
> +        raise TypeError(f"{snapshot_count} value is not an integer number")
Hopefully we never reach etcd  - 3.10/stable

```suggestion
    SNAPSHOT_COUNT_PRIOR_32 = 10000
    SNAPSHOT_COUNT_BEYOND_32 = 100000

    if snapshot_count == "auto":
        if channel == "auto":
            return SNAPSHOT_COUNT_BEYOND_32
        maj, min = map(int, c.split("/")[0].split("."))
        if (maj, min) >= (3, 2)
            return SNAPSHOT_COUNT_BEYOND_32
        return SNAPSHOT_COUNT_PRIOR_32
    try:
        return int(snapshot_count)
    except ValueError:
        raise TypeError(f"{snapshot_count} value is not an integer number")
```
```

2025-01-23 06:57 UTC, HomayoonAlimohammadi commented on lib/etcd_lib.py
> +        raise TypeError(f"{snapshot_count} value is not an integer number")
That's a really good point. We can also use `Version` for that matter.
```python
from packaging.version import Version
Version("2.3.1") > Version("10.1.2")  # False
```

2025-01-23 13:27 UTC, FrancescoDeSimone commented on lib/etcd_lib.py
> +        raise TypeError(f"{snapshot_count} value is not an integer number")
@HomayoonAlimohammadi TIL, thanks

2025-01-23 14:36 UTC, addyess approved these changes
Beautiful work. LGTM  🍰

2025-01-23 15:13 UTC, addyess commented
odd... the first run of the integration tests failed to complete `test_snapshot_restore`
* https://github.com/charmed-kubernetes/layer-etcd/actions/runs/12931100090/attempts/2?pr=213

I'll run again and see if it is successful

2025-01-23 15:42 UTC, addyess commented
@FrancescoDeSimone well I guess it wasn't a fluke.  The integration tests are failing in `test_snapshot_restore` due to these changes.  DO you have time to look into why this failure occurs?

2025-01-24 09:17 UTC, HomayoonAlimohammadi commented on lib/etcd_lib.py
> +        if channel == "auto" or Version(CHANNEL) >= Version("3.2"):
Just a minor question. Shouldn't this be an `and`?

2025-01-27 18:52 UTC, FrancescoDeSimone commented
hi @addyess try to understand what's the issue. Don't seems related to my changes. I tried to run the same test on the main branch and I got the same results

```
======================================== short test summary info =========================================
FAILED tests/integration/test_etcd.py::test_snapshot_restore - AssertionError: assert 'failed' == 'completed'
========================= 1 failed, 10 passed, 6 warnings in 1190.96s (0:19:50) ==========================
integration: exit 1 (1191.70 seconds) /home/ubuntu/test/layer-etcd> pytest -v -s --tb native --log-cli-level=INFO /home/ubuntu/test/layer-etcd/tests/integration pid=110510
  integration: FAIL code 1 (1204.01=setup[12.31]+cmd[1191.70] seconds)
  evaluation failed :( (1204.08 seconds)
ubuntu@ubuntu:~/test/layer-etcd$ git branch
* main
```


looks something relative to getent binary. I will try to dig deeper 

```
unit-etcd-1: 18:48:14 ERROR unit.etcd/1.juju-log b'cmd_run.go:1276: WARNING: cannot create user data directory: cannot get the current user: getent could not be executed: exec: "getent": executable file not found in $PATH\ncmd_run.go:1281: WARNING: cannot copy user Xauthority file: cannot get the current user: getent could not be executed: exec: "getent": executable file not found in $PATH\nCouldn\'t find a member in the cluster with an ID of cmd_run.go.\n'
```

2025-01-27 19:30 UTC, FrancescoDeSimone commented
@addyess I am currently facing the same problem with the upstream etcd, running this script 
```
juju add-model test
juju deploy easyrsa 
juju deploy ch:etcd --to 0
juju relate etcd easyrsa
juju wait-for application etcd
juju run etcd/leader snapshot
juju scp etcd/leader:"/home/ubuntu/etcd-snapshots/etcd-snapshot-*.tar.gz" snapshot.tar.gz 
juju attach-resource etcd snapshot=./snapshot.tar.gz
juju run etcd/leader restore
```
got the same error in juju debug-log
```
unit-etcd-0: 19:29:27 ERROR unit.etcd/0.juju-log b'cmd_run.go:1276: WARNING: cannot create user data directory: cannot get the current user: getent could not be executed: exec: "getent": executable file not found in $PATH\ncmd_run.go:1281: WARNING: cannot copy user Xauthority file: cannot get the current user: getent could not be executed: exec: "getent": executable file not found in $PATH\nCouldn\'t find a member in the cluster with an ID of cmd_run.go.\n'
```

2025-01-28 05:07 UTC, addyess commented
This will pass once the following is merged
* https://github.com/charmed-kubernetes/layer-etcd/pull/215

2025-01-28 16:10 UTC, addyess commented
@FrancescoDeSimone please rebase from main

2025-01-29 07:53 UTC, merged